packages:
  apt:
    - git
    - vim
    - curl
    - gnome-tweaks
    - software-properties-common
    - fish
  snap:
    - s
  ppa:
    - sublime-text
    - php7.2-{common, cli, fpm}
    - php7.4-{common, cli, fpm}
  deb:

repositories:
  add-apt:
    - ppa:ondrej/php
  dpkg:
    - google-chrome-stable_current_amd64
  custom:
    - wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null && echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
    - curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish

settings:
  git:
    name: m.pestov
    email: ddemoneno4ec@gmail.com
    ssh_dir: ''


after-install:
  fish:
    - chsh -s /usr/bin/fish
    - cp ./.config/fish/config.fish ~/.config/fish/config.fish
    - fish_add_path /usr/local/go/bin
  omf:
    - omf theme bobthefish
    - omf install bobthefish

# !TODO тут надо оптимизировать, пока просто вставил
fonts:
  Roboto:
    - git clone --depth 1 git@github.com:ryanoasis/nerd-fonts.git
  Ubuntu: # TODO после ещё надо настроить конфиги в терминале
    - sudo apt install wget fontconfig \
    && wget -P ~/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/latest/download/RobotoMono.zip \
    && cd ~/.local/share/fonts && unzip *.zip && rm *.zip && fc-cache -fv
  