packages:
  apt:
    - git
    - vim
    - curl
    - gnome-tweaks
    - software-properties-common
  snap:
    - s
  ppa:
    - sublime-text
    - php7.2-{common, cli, fpm}
    - php7.4-{common, cli, fpm}
  deb:

repositories:
  add-apt:
    - ppa:ondrej/php
  dpkg:
    - google-chrome-stable_current_amd64
  custom:
    - wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null && echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

settings:
  git:
    name: m.pestov
    email: ddemoneno4ec@gmail.com
    ssh_dir: ''